'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Entities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Entities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property companies() As DbSet(Of company)
    Public Overridable Property divisions() As DbSet(Of division)
    Public Overridable Property eventts() As DbSet(Of eventt)
    Public Overridable Property results() As DbSet(Of result)
    Public Overridable Property users() As DbSet(Of user)

End Class
